; Funções Globais
extern init_game
extern update_game
extern load_level
extern try_player_move
extern is_wall
extern respawn_all_enemies
extern spawn_single_enemy
extern update_all_enemies_ai
extern random_num_1_8

; Dados Globais
extern map
extern player_x
extern player_y
extern player_hp
extern steps
extern current_level

; Dados de Inimigos
extern enemies_x
extern enemies_y
extern enemies_hp
extern active_enemies